# Listar todos IMC
GET http://localhost:5204/api/imc/listar

###

# Listar IMC por Aluno
GET http://localhost:5204/api/imc/listarporaluno/1



###

# Criar IMC
POST http://localhost:5204/api/imc/cadastrar
Content-Type: application/json

{
  "alunoId": 1,
  "valor": 22.86
}

###

# Atualizar IMC
PUT http://localhost:5204/api/imc/alterar/1
Content-Type: application/json

{
  "valor": 23.50
}

###

# Cadastrar Aluno
POST http://localhost:5204/api/aluno/cadastrar
Content-Type: application/json

{
  "nome": "John Doe",
  "altura": 1.75,
  "peso": 70
}

###






